// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeApp.Data;

#nullable disable

namespace RecipeApp.Migrations
{
    [DbContext(typeof(RecipeDbContext))]
    [Migration("20260325080111_Phase4")]
    partial class Phase4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RecipeApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "🥗",
                            Name = "Vorspeisen",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Icon = "🍽️",
                            Name = "Hauptgerichte",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Icon = "🍨",
                            Name = "Desserts",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Icon = "🥬",
                            Name = "Salate",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Icon = "🥣",
                            Name = "Suppen",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Icon = "🥨",
                            Name = "Snacks",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            Icon = "🥤",
                            Name = "Getränke",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            Icon = "🍰",
                            Name = "Backen",
                            SortOrder = 8
                        });
                });

            modelBuilder.Entity("RecipeApp.Models.MealPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("MealType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("RecipeApp.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CookingTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("IngredientsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstructionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Servings")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CookingTimeMinutes = 20,
                            CreatedAt = new DateTime(2026, 3, 25, 8, 1, 10, 683, DateTimeKind.Utc).AddTicks(3678),
                            Description = "Der italienische Klassiker mit Speck und Ei.",
                            Difficulty = 1,
                            IngredientsJson = "[\"400g Spaghetti\",\"150g Guanciale (oder Pancetta)\",\"4 Eier\",\"100g Pecorino Romano\",\"Schwarzer Pfeffer\"]",
                            InstructionsJson = "[\"Nudeln in Salzwasser al dente kochen.\",\"Guanciale in einer Pfanne knusprig braten.\",\"Eier und geriebenen Pecorino verquirlen.\",\"Nudeln abtropfen lassen und zum Speck in die Pfanne geben (vom Herd nehmen!).\",\"Ei-K\\u00E4se-Mischung unterr\\u00FChren, bis eine cremige Sauce entsteht. Mit Pfeffer w\\u00FCrzen.\"]",
                            Servings = 4,
                            Tags = "Italienisch, Pasta, Schnell",
                            Title = "Spaghetti Carbonara",
                            UpdatedAt = new DateTime(2026, 3, 25, 8, 1, 10, 683, DateTimeKind.Utc).AddTicks(3680)
                        },
                        new
                        {
                            Id = 2,
                            CookingTimeMinutes = 30,
                            CreatedAt = new DateTime(2026, 3, 25, 8, 1, 10, 683, DateTimeKind.Utc).AddTicks(3866),
                            Description = "Deftige Spätzle mit reichlich Käse und Röstzwiebeln.",
                            Difficulty = 0,
                            IngredientsJson = "[\"500g Sp\\u00E4tzle\",\"200g Emmentaler\",\"100g Bergk\\u00E4se\",\"2 gro\\u00DFe Zwiebeln\",\"2 EL Butter\",\"Salz, Pfeffer, Muskatnuss\"]",
                            InstructionsJson = "[\"Zwiebeln in Ringe schneiden und in Butter goldbraun r\\u00F6sten.\",\"Sp\\u00E4tzle nach Packungsanweisung kochen.\",\"K\\u00E4se reiben.\",\"Sp\\u00E4tzle und K\\u00E4se abwechselnd in eine Pfanne schichten.\",\"Schmelzen lassen, w\\u00FCrzen und mit R\\u00F6stzwiebeln garnieren.\"]",
                            Servings = 3,
                            Tags = "Deutsch, Vegetarisch, Deftig",
                            Title = "Käsespätzle",
                            UpdatedAt = new DateTime(2026, 3, 25, 8, 1, 10, 683, DateTimeKind.Utc).AddTicks(3867)
                        },
                        new
                        {
                            Id = 3,
                            CookingTimeMinutes = 140,
                            CreatedAt = new DateTime(2026, 3, 25, 8, 1, 10, 683, DateTimeKind.Utc).AddTicks(3947),
                            Description = "Klassisches ungarisches Gulasch, stundenlang geschmort.",
                            Difficulty = 1,
                            IngredientsJson = "[\"800g Rindfleisch (Gulasch)\",\"800g Zwiebeln\",\"2 EL Paprikapulver edels\\u00FC\\u00DF\",\"1 TL K\\u00FCmmel\",\"2 EL Tomatenmark\",\"750ml Rinderbr\\u00FChe\"]",
                            InstructionsJson = "[\"Zwiebeln grob w\\u00FCrfeln.\",\"Fleisch scharf anbraten, aus dem Topf nehmen.\",\"Zwiebeln im Bratfett anr\\u00F6sten, Tomatenmark und Paprikapulver kurz mitr\\u00F6sten.\",\"Mit Br\\u00FChe abl\\u00F6schen, Fleisch zur\\u00FCckgeben.\",\"Mindestens 2 Stunden bei schwacher Hitze schmoren lassen. Mit Salz, Pfeffer und K\\u00FCmmel abschmecken.\"]",
                            Servings = 4,
                            Tags = "Fleisch, Schmoren, Hausmannskost",
                            Title = "Rindergulasch",
                            UpdatedAt = new DateTime(2026, 3, 25, 8, 1, 10, 683, DateTimeKind.Utc).AddTicks(3948)
                        },
                        new
                        {
                            Id = 4,
                            CookingTimeMinutes = 25,
                            CreatedAt = new DateTime(2026, 3, 25, 8, 1, 10, 683, DateTimeKind.Utc).AddTicks(4020),
                            Description = "Süße österreichische Spezialität, fluffig und karamellisiert.",
                            Difficulty = 1,
                            IngredientsJson = "[\"4 Eier\",\"125ml Milch\",\"100g Mehl\",\"2 EL Zucker\",\"Prise Salz\",\"3 EL Butter\",\"Puderzucker zum Best\\u00E4uben\"]",
                            InstructionsJson = "[\"Eier trennen. Eiwei\\u00DF mit Salz steif schlagen.\",\"Eigelb mit Milch, Mehl und Zucker glatt r\\u00FChren.\",\"Eischnee vorsichtig unterheben.\",\"Butter in einer gro\\u00DFen Pfanne schmelzen, Teig eingie\\u00DFen und stocken lassen.\",\"Wenden, in mundgerechte St\\u00FCcke rei\\u00DFen und mit etwas Zucker karamellisieren.\",\"Mit Puderzucker best\\u00E4ubt servieren.\"]",
                            Servings = 2,
                            Tags = "Süßspeise, Österreichisch, Dessert",
                            Title = "Kaiserschmarrn",
                            UpdatedAt = new DateTime(2026, 3, 25, 8, 1, 10, 683, DateTimeKind.Utc).AddTicks(4021)
                        },
                        new
                        {
                            Id = 5,
                            CookingTimeMinutes = 60,
                            CreatedAt = new DateTime(2026, 3, 25, 8, 1, 10, 683, DateTimeKind.Utc).AddTicks(4098),
                            Description = "Eine einfache, wärmende Suppe für kalte Tage.",
                            Difficulty = 0,
                            IngredientsJson = "[\"250g Tellerlinsen\",\"1 Bund Suppengr\\u00FCn\",\"2 Kartoffeln\",\"1 Zwiebel\",\"1 Liter Gem\\u00FCsebr\\u00FChe\",\"2 Paar Wiener W\\u00FCrstchen\",\"1 EL Essig\"]",
                            InstructionsJson = "[\"Zwiebel w\\u00FCrfeln, Suppengr\\u00FCn und Kartoffeln putzen und klein schneiden.\",\"Zwiebeln and\\u00FCnsten, Linsen und restliches Gem\\u00FCse zugeben.\",\"Mit Br\\u00FChe aufgie\\u00DFen und ca. 45 Minuten kochen lassen.\",\"W\\u00FCrstchen in Scheiben schneiden und in der Suppe erw\\u00E4rmen.\",\"Mit Salz, Pfeffer und etwas Essig abschmecken.\"]",
                            Servings = 4,
                            Tags = "Suppe, Hausmannskost, Günstig",
                            Title = "Linsensuppe",
                            UpdatedAt = new DateTime(2026, 3, 25, 8, 1, 10, 683, DateTimeKind.Utc).AddTicks(4098)
                        });
                });

            modelBuilder.Entity("RecipeCategory", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoriesId", "RecipesId");

                    b.HasIndex("RecipesId");

                    b.ToTable("RecipeCategory");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecipeApp.Models.MealPlan", b =>
                {
                    b.HasOne("RecipeApp.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecipeApp.Models.Recipe", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("RecipeCategory", b =>
                {
                    b.HasOne("RecipeApp.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeApp.Models.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
